import { LabTest, StaffMember, LabLocation, HealthPackage } from './types';

export const STAFF_MEMBERS: StaffMember[] = [];

export const LAB_LOCATIONS: LabLocation[] = [
  {
    id: 'loc-1',
    name: 'Jhansi Labs Main Center & Office',
    address: 'Bajrang Colony, Jhansi, Uttar Pradesh',
    phone: '+91 9838319144',
    isMain: true,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
  },
];

export const HEALTH_PACKAGES: HealthPackage[] = [
  {
    id: 'pkg-01',
    name: 'Arthritis Basic Screening',
    price: 800,
    originalPrice: 1199,
    description: 'Basic screening for arthritis related concerns.',
    testsIncluded: ['Arthritis Screening Tests'],
    image: 'https://images.unsplash.com/photo-1505751172107-573225a91200?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'pkg-02',
    name: 'Basic Health Checkup',
    price: 250,
    originalPrice: 799,
    description: 'Essential screening for overall health monitoring.',
    testsIncluded: ['Basic Health Tests'],
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'pkg-03',
    name: 'Comprehensive Full Body Checkup with Vitamin D',
    price: 1100,
    originalPrice: 1549,
    description: 'Comprehensive health assessment including Vitamin D.',
    testsIncluded: ['Full Body Tests', 'Vitamin D'],
    image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'pkg-04',
    name: 'Covid Well',
    price: 1800,
    originalPrice: 2599,
    description: 'Post-Covid health monitoring package.',
    testsIncluded: ['Covid Recovery Markers'],
    image: 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'pkg-05',
    name: 'Fever Plus Profile',
    price: 1300,
    originalPrice: 1760,
    description: 'Detailed profile for persistent fever investigation.',
    testsIncluded: ['Fever Markers', 'Infection Screening'],
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'pkg-06',
    name: 'Fever Profile',
    price: 650,
    originalPrice: 900,
    description: 'Basic fever screening profile.',
    testsIncluded: ['Fever Basic Markers'],
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'pkg-07',
    name: 'Freedom A - 2022',
    price: 1800,
    originalPrice: 2500,
    description: 'Comprehensive health screening package.',
    testsIncluded: ['Freedom A Test Set'],
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'pkg-08',
    name: 'Freedom B - 2022',
    price: 2200,
    originalPrice: 3000,
    description: 'Advanced healthcare assessment package.',
    testsIncluded: ['Freedom B Test Set'],
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'pkg-09',
    name: 'JL Advance Men Package',
    price: 1600,
    originalPrice: 2200,
    description: 'Advanced health screening for men.',
    testsIncluded: ['Male Specific Tests', 'Organ Function'],
    image: 'https://images.unsplash.com/photo-1511174511562-5f7f18b874f8?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'pkg-10',
    name: 'JL Comprehensive Monsoon Package',
    price: 1500,
    originalPrice: 2000,
    description: 'Special screening for monsoon-related illnesses.',
    testsIncluded: ['Monsoon Markers'],
    image: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'pkg-11',
    name: 'JL Diabetic Pro',
    price: 2100,
    originalPrice: 3060,
    description: 'Professional diabetic monitoring and management package.',
    testsIncluded: ['HbA1c', 'Blood Sugar', 'Complication Screening'],
    image: 'https://images.unsplash.com/photo-1505751172107-573225a91200?auto=format&fit=crop&q=80&w=600',
  },
];

export const TEST_CATEGORIES = [
  'All',
  'Blood Test',
  'Biopsy',
  'Culture',
  'Hormone',
  'Diabetes',
  'Thyroid',
  'Heart',
  'Kidney',
  'Liver',
  'Vitamins',
  'Immunology',
  'Urine Test',
];

export const AVAILABLE_TESTS: LabTest[] = [
  { id: '01', name: '17 OH Progesterone', category: 'Hormone', price: 700, description: 'Measures 17-hydroxyprogesterone levels.' },
  { id: '02', name: '24 hour Albumin creatinine ratio (ACR)', category: 'Kidney', price: 600, description: 'Measures albumin and creatinine in 24-hour urine.' },
  { id: '03', name: '24 Hours Protein Creatinine Ratio (PCR)', category: 'Kidney', price: 600, description: 'Measures protein and creatinine in 24-hour urine.' },
  { id: '04', name: '24 Hours Urinary Uric Acid', category: 'Urine Test', price: 200, description: 'Measures uric acid in 24-hour urine.' },
  { id: '05', name: '24 Hrs Urinary Calcium', category: 'Urine Test', price: 210, description: 'Measures calcium in 24-hour urine.' },
  { id: '06', name: '24 Hrs Urinary Proteins', category: 'Urine Test', price: 315, description: 'Measures proteins in 24-hour urine.' },
  { id: '07', name: '24 Hrs Urinary Sodium', category: 'Urine Test', price: 200, description: 'Measures sodium in 24-hour urine.' },
  { id: '08', name: '25 OH Vitamin D', category: 'Vitamins', price: 800, description: 'Measures Vitamin D levels.' },
  { id: '09', name: 'Abdomen mass biopsy -Medium 1-3 cm', category: 'Biopsy', price: 750, description: 'Biopsy of abdomen mass.' },
  { id: '10', name: 'ABO Blood Group and Rh Type', category: 'Blood Test', price: 170, description: 'Determines blood group and Rh factor.' },
  { id: '11', name: 'Acetyl Choline Receptor Antibodies (AChRab)', category: 'Immunology', price: 3300, description: 'Tests for Myasthenia Gravis.' },
  { id: '12', name: 'Acid Fast Bacilli Smear', category: 'Culture', price: 300, description: 'Smear for TB detection.' },
  { id: '13', name: 'Acid Phosphatase', category: 'Blood Test', price: 350, description: 'Measures acid phosphatase levels.' },
  { id: '14', name: 'ACTH (Adreno Corticotropic Hormone)', category: 'Hormone', price: 1250, description: 'Measures ACTH levels.' },
  { id: '15', name: 'Adenosine Deaminase (ADA)', category: 'Blood Test', price: 580, description: 'Measures ADA levels.' },
  { id: '16', name: 'Adenosine Deaminase (ADA)(Ascitic fluid)', category: 'Blood Test', price: 580, description: 'Measures ADA in ascitic fluid.' },
  { id: '17', name: 'Adenosine Deaminase (ADA)(CSF)', category: 'Blood Test', price: 580, description: 'Measures ADA in CSF.' },
  { id: '18', name: 'Adenosine Deaminase (ADA)(Pleural fluid)', category: 'Blood Test', price: 900, description: 'Measures ADA in pleural fluid.' },
  { id: '19', name: 'Adenosine Deaminase (ADA)(Pus)', category: 'Blood Test', price: 900, description: 'Measures ADA in pus.' },
  { id: '20', name: 'AFB Rapid culture by MGIT - Tissue/Biopsy', category: 'Culture', price: 1800, description: 'Rapid culture for AFB.' },
  { id: '21', name: 'AFB-detection by smear examination ZN Stain Body fluids', category: 'Culture', price: 350, description: 'AFB detection in body fluids.' },
  { id: '22', name: 'AFB-detection by smear examination ZN Stain Sputum, 1 samples', category: 'Culture', price: 350, description: 'AFB detection in sputum.' },
  { id: '23', name: 'AFB-detection by smear examination ZN Stain Urine, 1 samples', category: 'Culture', price: 350, description: 'AFB detection in urine.' },
  { id: '24', name: 'AFB-DNA (TB-PCR) Detection by RTPCR, Reflex to Rifampicin resistance by Ultra CBNAAT', category: 'Culture', price: 2150, description: 'TB-PCR detection.' },
  { id: '25', name: 'AFB-Xpert panel (M.Tb Detection & Rifamipicin resistance) by CBNAAT - Extra pulmonary samples', category: 'Culture', price: 2750, description: 'Xpert panel for extra pulmonary samples.' },
  { id: '26', name: 'AFB-Xpert panel (M.Tb Detection & Rifamipicin resistance) by CBNAAT - Pulmonary samples', category: 'Culture', price: 2750, description: 'Xpert panel for pulmonary samples.' },
  { id: '27', name: 'Alanine Transaminase (SGPT)', category: 'Liver', price: 100, description: 'Liver enzyme test.' },
  { id: '28', name: 'Albumin', category: 'Blood Test', price: 100, description: 'Measures albumin levels.' },
  { id: '29', name: 'Albumin creatinine ratio (ACR) - Spot sample', category: 'Kidney', price: 600, description: 'Measures ACR in spot urine.' },
  { id: '30', name: 'Alcohol Ethanol Serum', category: 'Blood Test', price: 1100, description: 'Measures alcohol levels in serum.' },
  { id: '31', name: 'Aldosterone', category: 'Hormone', price: 2200, description: 'Measures aldosterone levels.' },
  { id: '32', name: 'Alkaline Phosphatase', category: 'Liver', price: 150, description: 'Measures alkaline phosphatase levels.' },
  { id: '33', name: 'Allergen, Individual-Micro organism Aspergillus Fumigatus fungus', category: 'Immunology', price: 1250, description: 'Tests for Aspergillus Fumigatus allergy.' },
  { id: '34', name: 'Alpha Feto Protein (AFP)', category: 'Blood Test', price: 650, description: 'Tumor marker test.' },
  { id: '35', name: 'Amylase', category: 'Blood Test', price: 350, description: 'Measures amylase levels.' },
  { id: '36', name: 'ANA Screening by IFA', category: 'Immunology', price: 900, description: 'Screening for autoimmune disorders.' },
  { id: '37', name: 'Androstenedione (A4)', category: 'Hormone', price: 2050, description: 'Measures androstenedione levels.' },
  { id: '38', name: 'Angiotensin Converting Enzyme (ACE)', category: 'Blood Test', price: 1250, description: 'Measures ACE levels.' },
  { id: '39', name: 'ANTI CCP (ACCP)', category: 'Immunology', price: 900, description: 'Tests for Rheumatoid Arthritis.' },
  { id: '40', name: 'Anti Chlamydia Antibody Igm', category: 'Immunology', price: 1200, description: 'Tests for Chlamydia infection.' },
  { id: '41', name: 'Anti Ds-DNA', category: 'Immunology', price: 100, description: 'Tests for SLE.' },
  { id: '42', name: 'Anti HCV IgM', category: 'Immunology', price: 1800, description: 'Tests for Hepatitis C.' },
  { id: '43', name: 'Anti Hepatitis A Virus (ANTI HAV) - IgG', category: 'Immunology', price: 680, description: 'Tests for Hepatitis A immunity.' },
  { id: '44', name: 'Anti Hepatitis A Virus (ANTI HAV) - IgM', category: 'Immunology', price: 700, description: 'Tests for acute Hepatitis A.' },
  { id: '45', name: 'Anti Hepatitis B Core Antibody (AHBC) - IGM', category: 'Immunology', price: 650, description: 'Tests for acute Hepatitis B.' },
  { id: '46', name: 'Anti Hepatitis B Core Antibody (AHBc) - Total', category: 'Immunology', price: 750, description: 'Tests for past or current Hepatitis B.' },
  { id: '47', name: 'Anti Hepatitis B Envelope Antibody (AHBe) -Total', category: 'Immunology', price: 700, description: 'Tests for Hepatitis B envelope antibody.' },
  { id: '48', name: 'Anti Hepatitis C Virus (HCV) - Total', category: 'Immunology', price: 550, description: 'Screening for Hepatitis C.' },
  { id: '49', name: 'Anti Hepatitis E Virus (HEV) - IgG', category: 'Immunology', price: 910, description: 'Tests for Hepatitis E immunity.' },
  { id: '50', name: 'Anti Hepatitis E Virus (HEV) - IgM', category: 'Immunology', price: 700, description: 'Tests for acute Hepatitis E.' },
  { id: '51', name: 'Anti Mitochondrial Antibody', category: 'Immunology', price: 1680, description: 'Tests for primary biliary cirrhosis.' },
  { id: '52', name: 'Anti Mullerian Hormone (AMH)', category: 'Hormone', price: 1800, description: 'Measures ovarian reserve.' },
  { id: '53', name: 'Anti Nuclear Antibodies (ANA)', category: 'Immunology', price: 550, description: 'Tests for autoimmune disorders.' },
  { id: '54', name: 'Anti Phospholipid Antibody (APL) - IgG', category: 'Immunology', price: 650, description: 'Tests for antiphospholipid syndrome.' },
  { id: '55', name: 'Anti Phospholipid Antibody (APL) - IgM', category: 'Immunology', price: 650, description: 'Tests for antiphospholipid syndrome.' },
  { id: '56', name: 'Anti TPO', category: 'Thyroid', price: 1000, description: 'Tests for thyroid antibodies.' },
  { id: '57', name: 'Anti-Hepatitis B Surface antibodies (Anti-HBs titre)', category: 'Immunology', price: 500, description: 'Measures immunity to Hepatitis B.' },
  { id: '58', name: 'Anti-microsomal antibodies', category: 'Thyroid', price: 1100, description: 'Tests for thyroid antibodies.' },
  { id: '59', name: 'Anti-ro SSA Antibodies by EIA', category: 'Immunology', price: 1800, description: 'Tests for autoimmune disorders.' },
  { id: '60', name: 'Anti-Smooth Muscle Antibody', category: 'Immunology', price: 1800, description: 'Tests for autoimmune hepatitis.' },
  { id: '61', name: 'Anti-Streptolysin O (ASO)', category: 'Blood Test', price: 450, description: 'Tests for recent strep infection.' },
  { id: '62', name: 'Apo B: Apo A1 ratio', category: 'Heart', price: 850, description: 'Apolipoprotein ratio for heart risk.' },
  { id: '63', name: 'Apolipoprotein - A1', category: 'Heart', price: 450, description: 'Measures Apolipoprotein A1.' },
  { id: '64', name: 'Apolipoprotein - B', category: 'Heart', price: 450, description: 'Measures Apolipoprotein B.' },
  { id: '65', name: 'Appendix -Large Biopsy 3-6 cm', category: 'Biopsy', price: 1000, description: 'Biopsy of appendix mass.' },
  { id: '66', name: 'APTT', category: 'Blood Test', price: 400, description: 'Measures blood clotting time.' },
  { id: '67', name: 'Aspartate AminoTransferase (SGOT)', category: 'Liver', price: 150, description: 'Liver enzyme test.' },
  { id: '68', name: 'Aspergillosis IgG antibodies', category: 'Immunology', price: 2000, description: 'Tests for Aspergillus infection.' },
  { id: '69', name: 'Aspergillosis IgM antibodies', category: 'Immunology', price: 2100, description: 'Tests for acute Aspergillus infection.' },
  { id: '70', name: 'Beta 2 Glycoprotein 1 - IgG', category: 'Immunology', price: 1000, description: 'Tests for antiphospholipid syndrome.' },
  { id: '71', name: 'Beta 2 Glycoprotein 1 - IgM', category: 'Immunology', price: 1000, description: 'Tests for antiphospholipid syndrome.' },
  { id: '72', name: 'Beta 2 Microglobulin', category: 'Blood Test', price: 1200, description: 'Tumor marker and kidney function test.' },
  { id: '73', name: 'Beta HCG', category: 'Hormone', price: 450, description: 'Pregnancy and tumor marker test.' },
  { id: '74', name: 'Beta-Thalassemia Screenig with Graph', category: 'Blood Test', price: 350, description: 'Screening for Thalassemia.' },
  { id: '75', name: 'Bicarbonate', category: 'Blood Test', price: 350, description: 'Measures bicarbonate levels.' },
  { id: '76', name: 'Bile Acids', category: 'Liver', price: 1800, description: 'Measures bile acid levels.' },
  { id: '77', name: 'Bilirubin Direct', category: 'Liver', price: 100, description: 'Measures direct bilirubin.' },
  { id: '78', name: 'Bilirubin Total', category: 'Liver', price: 100, description: 'Measures total bilirubin.' },
  { id: '79', name: 'Biotinidase Enzyme Activity', category: 'Blood Test', price: 500, description: 'Measures biotinidase activity.' },
  { id: '80', name: 'Blood C/S - BacT/Alert (with bottle)', category: 'Culture', price: 800, description: 'Blood culture with bottle.' },
  { id: '81', name: 'Blood C/S - BacT/Alert (without bottle)', category: 'Culture', price: 700, description: 'Blood culture without bottle.' },
  { id: '82', name: 'Blood Toxic Element Profile', category: 'Blood Test', price: 900, description: 'Profile for toxic elements in blood.' },
  { id: '83', name: 'Blood Urea Nitrogen (BUN)', category: 'Kidney', price: 100, description: 'Measures blood urea nitrogen.' },
  { id: '84', name: 'Body Fluid Analysis - Plerual Fluid', category: 'Blood Test', price: 1000, description: 'Analysis of pleural fluid.' },
  { id: '85', name: 'Body Fluid Analysis (Other) - Body Fluid', category: 'Blood Test', price: 1000, description: 'Analysis of other body fluids.' },
  { id: '86', name: 'Body Fluid Analysis -Ascitic Fluid', category: 'Blood Test', price: 1000, description: 'Analysis of ascitic fluid.' },
  { id: '87', name: 'Body fluid analysis for malignant cells', category: 'Biopsy', price: 950, description: 'Analysis for malignancy.' },
  { id: '88', name: 'Breast biopsy -Medium 1-3 cm', category: 'Biopsy', price: 900, description: 'Biopsy of breast mass.' },
  { id: '89', name: 'Breast biopsy -small <1cm', category: 'Biopsy', price: 600, description: 'Biopsy of small breast mass.' },
  { id: '90', name: 'Breast lump', category: 'Biopsy', price: 900, description: 'Analysis of breast lump.' },
  { id: '91', name: 'Brucella IgM', category: 'Immunology', price: 1650, description: 'Tests for Brucellosis.' },
  { id: '92', name: 'BUN/Creatinine ratio', category: 'Kidney', price: 150, description: 'Ratio of BUN to creatinine.' },
  { id: '93', name: 'C - Reactive Protein (CRP)', category: 'Immunology', price: 300, description: 'Measures inflammation.' },
  { id: '94', name: 'CA 19.9', category: 'Blood Test', price: 900, description: 'Tumor marker for pancreatic cancer.' },
  { id: '95', name: 'CA125', category: 'Blood Test', price: 900, description: 'Tumor marker for ovarian cancer.' },
  { id: '96', name: 'CA15.3', category: 'Blood Test', price: 900, description: 'Tumor marker for breast cancer.' },
  { id: '97', name: 'Calcitonin', category: 'Hormone', price: 2200, description: 'Measures calcitonin levels.' },
  { id: '98', name: 'Calcium', category: 'Blood Test', price: 120, description: 'Measures calcium levels.' },
  { id: '99', name: 'Calcium creatinine ratio (Spot)', category: 'Kidney', price: 450, description: 'Ratio in spot urine.' },
  { id: '100', name: 'Calprotectin', category: 'Blood Test', price: 3000, description: 'Marker for intestinal inflammation.' },
  { id: '101', name: 'Carcino Embryonic Antigen (CEA)', category: 'Blood Test', price: 500, description: 'Tumor marker test.' },
  { id: '102', name: 'Cardiolipin Antibody (ACL) -IgA', category: 'Immunology', price: 550, description: 'Tests for antiphospholipid syndrome.' },
  { id: '103', name: 'Cardiolipin Antibody (ACL) -IgG', category: 'Immunology', price: 500, description: 'Tests for antiphospholipid syndrome.' },
  { id: '104', name: 'Cardiolipin Antibody (ACL) -IgM', category: 'Immunology', price: 550, description: 'Tests for antiphospholipid syndrome.' },
  { id: '105', name: 'CBC-Complete Blood Count', category: 'Blood Test', price: 180, description: 'Complete blood count.' },
  { id: '106', name: 'CBC-Complete Hemogram Test(28)', category: 'Blood Test', price: 180, description: 'Complete hemogram.' },
  { id: '107', name: 'CD3/CD4/CD8', category: 'Blood Test', price: 1100, description: 'Measures T-cell subsets.' },
  { id: '108', name: 'Ceruloplasmin', category: 'Blood Test', price: 1000, description: 'Measures ceruloplasmin levels.' },
  { id: '109', name: 'Cervix biopsy -Medium 1-3 cm', category: 'Biopsy', price: 750, description: 'Biopsy of cervix mass.' },
  { id: '110', name: 'Cervix biopsy -small <1cm', category: 'Biopsy', price: 600, description: 'Biopsy of small cervix mass.' },
  { id: '111', name: 'Cheek biopsy -small <1cm', category: 'Biopsy', price: 650, description: 'Biopsy of small cheek mass.' },
  { id: '112', name: 'Chikungunya Combo Rapid Test', category: 'Immunology', price: 1000, description: 'Rapid test for Chikungunya.' },
  { id: '113', name: 'Chikungunya IgG Rapid antibody', category: 'Immunology', price: 800, description: 'Tests for Chikungunya IgG.' },
  { id: '114', name: 'Chikungunya IgM Rapid antibody', category: 'Immunology', price: 700, description: 'Tests for Chikungunya IgM.' },
  { id: '115', name: 'Chloride', category: 'Blood Test', price: 200, description: 'Measures chloride levels.' },
  { id: '116', name: 'Colon biopsy -small <1cm', category: 'Biopsy', price: 600, description: 'Biopsy of small colon mass.' },
  { id: '117', name: 'Complement 3 (C3)', category: 'Immunology', price: 500, description: 'Measures C3 levels.' },
  { id: '118', name: 'Complement 4 (C4)', category: 'Immunology', price: 500, description: 'Measures C4 levels.' },
  { id: '119', name: 'Cortisol (4:00 PM)', category: 'Hormone', price: 500, description: 'Measures afternoon cortisol.' },
  { id: '120', name: 'Cortisol (8:00 AM)', category: 'Hormone', price: 500, description: 'Measures morning cortisol.' },
  { id: '121', name: 'Covid 19 Antibodies - Total', category: 'Immunology', price: 700, description: 'Tests for Covid-19 antibodies.' },
  { id: '122', name: 'C-Peptide Fasting', category: 'Diabetes', price: 900, description: 'Measures fasting C-peptide.' },
  { id: '123', name: 'C-Peptide PP', category: 'Diabetes', price: 900, description: 'Measures post-prandial C-peptide.' },
  { id: '124', name: 'Creatine Kinase-MB (CK-MB)', category: 'Heart', price: 600, description: 'Measures heart enzyme levels.' },
  { id: '125', name: 'Creatinine Phospho Kinase (CPK) - Total', category: 'Blood Test', price: 300, description: 'Measures CPK levels.' },
  { id: '126', name: 'Culture & Sensitivity, Aerobic bacteria Blood 1 Aerobic,1-Anerobic', category: 'Culture', price: 1800, description: 'Blood culture and sensitivity.' },
  { id: '127', name: 'Culture & Sensitivity, Aerobic bacteria Blood single bottle', category: 'Culture', price: 800, description: 'Blood culture and sensitivity.' },
  { id: '128', name: 'Culture & Sensitivity, Aerobic bacteria Body Fluids Specify type', category: 'Culture', price: 900, description: 'Body fluid culture and sensitivity.' },
  { id: '129', name: 'Culture & Sensitivity, Aerobic bacteria CSF', category: 'Culture', price: 900, description: 'CSF culture and sensitivity.' },
  { id: '130', name: 'Culture & Sensitivity, Aerobic bacteria Other samples', category: 'Culture', price: 1000, description: 'Other sample culture and sensitivity.' },
  { id: '131', name: 'Culture & Sensitivity, Aerobic bacteria Pus', category: 'Culture', price: 800, description: 'Pus culture and sensitivity.' },
  { id: '132', name: 'Culture & Sensitivity, Aerobic bacteria Semen', category: 'Culture', price: 800, description: 'Semen culture and sensitivity.' },
  { id: '133', name: 'Culture & Sensitivity, Aerobic bacteria Sputum', category: 'Culture', price: 800, description: 'Sputum culture and sensitivity.' },
  { id: '134', name: 'Culture & Sensitivity, Aerobic bacteria Stool', category: 'Culture', price: 800, description: 'Stool culture and sensitivity.' },
  { id: '135', name: 'Culture & Sensitivity, Aerobic bacteria Throat Swab', category: 'Culture', price: 800, description: 'Throat swab culture and sensitivity.' },
  { id: '136', name: 'Culture & Sensitivity, Aerobic bacteria Urine', category: 'Culture', price: 800, description: 'Urine culture and sensitivity.' },
  { id: '137', name: 'Cystatin - C', category: 'Kidney', price: 1400, description: 'Measures cystatin C levels.' },
  { id: '138', name: 'Cytomegalo Virus (CMV) - IgG', category: 'Immunology', price: 500, description: 'Tests for CMV IgG.' },
  { id: '139', name: 'Cytomegalo Virus (CMV) - IgM', category: 'Immunology', price: 550, description: 'Tests for CMV IgM.' },
  { id: '140', name: 'DCP-Decarboxy Prothrombin PIVKA-II', category: 'Blood Test', price: 3000, description: 'Tumor marker for liver cancer.' },
  { id: '141', name: 'D-DIMER', category: 'Blood Test', price: 1100, description: 'Tests for blood clots.' },
  { id: '142', name: 'Dengue -IgG (CLIA)', category: 'Immunology', price: 500, description: 'Tests for Dengue IgG.' },
  { id: '143', name: 'Dengue -IgG (ELISA)', category: 'Immunology', price: 500, description: 'Tests for Dengue IgG.' },
  { id: '144', name: 'Dengue IgG (Rapid)', category: 'Immunology', price: 250, description: 'Rapid test for Dengue IgG.' },
  { id: '145', name: 'Dengue -IgM (CLIA)', category: 'Immunology', price: 500, description: 'Tests for Dengue IgM.' },
  { id: '146', name: 'Dengue -IgM (ELISA)', category: 'Immunology', price: 500, description: 'Tests for Dengue IgM.' },
  { id: '147', name: 'Dengue IgM (Rapid)', category: 'Immunology', price: 250, description: 'Rapid test for Dengue IgM.' },
  { id: '148', name: 'Dengue NS-1 Antigen (CLIA)', category: 'Immunology', price: 500, description: 'Tests for Dengue NS1 antigen.' },
  { id: '149', name: 'Dengue NS-1 Antigen (ELISA)', category: 'Immunology', price: 500, description: 'Tests for Dengue NS1 antigen.' },
  { id: '150', name: 'Dengue NS-1 Antigen (Rapid)', category: 'Immunology', price: 250, description: 'Rapid test for Dengue NS1 antigen.' },
  { id: '151', name: 'Desmoglein I Antibody', category: 'Immunology', price: 2800, description: 'Tests for Pemphigus Foliaceus.' },
  { id: '152', name: 'Desmoglein III Antibody', category: 'Immunology', price: 2800, description: 'Tests for Pemphigus Vulgaris.' },
  { id: '153', name: 'DHEA-Sulphate (DHEAS)', category: 'Hormone', price: 800, description: 'Measures DHEAS levels.' },
  { id: '154', name: 'Di Hydro Testosterone (DHT)', category: 'Hormone', price: 1800, description: 'Measures DHT levels.' },
  { id: '155', name: 'Digoxin', category: 'Blood Test', price: 800, description: 'Measures digoxin levels.' },
  { id: '156', name: 'Double Marker', category: 'Hormone', price: 1500, description: 'Prenatal screening test.' },
  { id: '157', name: 'Dual Marker (PAPP-A + Free Beta HCG)', category: 'Hormone', price: 1500, description: 'Prenatal screening test.' },
  { id: '158', name: 'Electrolytes (Na, K, Cl)', category: 'Blood Test', price: 450, description: 'Measures sodium, potassium, and chloride.' },
  { id: '159', name: 'Endometrium biopsy -Medium 1-3 cm', category: 'Biopsy', price: 800, description: 'Biopsy of endometrium mass.' },
  { id: '160', name: 'Endometrium biopsy -small <1cm', category: 'Biopsy', price: 600, description: 'Biopsy of small endometrium mass.' },
  { id: '162', name: 'Estradiol (E2)', category: 'Hormone', price: 500, description: 'Measures estradiol levels.' },
  { id: '163', name: 'Estriol - Free (E3)', category: 'Hormone', price: 800, description: 'Measures free estriol levels.' },
  { id: '164', name: 'Factor VIII', category: 'Blood Test', price: 2800, description: 'Measures clotting factor VIII.' },
  { id: '165', name: 'Factor IX', category: 'Blood Test', price: 2800, description: 'Measures clotting factor IX.' },
  { id: '166', name: 'Ferritin', category: 'Blood Test', price: 600, description: 'Measures iron stores.' },
  { id: '167', name: 'Fibrinogen', category: 'Blood Test', price: 800, description: 'Measures fibrinogen levels.' },
  { id: '168', name: 'Filariasis antibody (Rapid)', category: 'Immunology', price: 600, description: 'Rapid test for Filariasis.' },
  { id: '169', name: 'Fine Needle Aspiration Cytology (FNAC)', category: 'Biopsy', price: 600, description: 'Cytology of fine needle aspirate.' },
  { id: '170', name: 'Fluid Albumin', category: 'Blood Test', price: 250, description: 'Measures albumin in body fluid.' },
  { id: '171', name: 'Fluid Amylase', category: 'Blood Test', price: 400, description: 'Measures amylase in body fluid.' },
  { id: '172', name: 'Fluid Cell Count & Differential', category: 'Blood Test', price: 300, description: 'Cell count of body fluid.' },
  { id: '173', name: 'Fluid Chloride', category: 'Blood Test', price: 250, description: 'Measures chloride in body fluid.' },
  { id: '174', name: 'Fluid Creatinine', category: 'Blood Test', price: 250, description: 'Measures creatinine in body fluid.' },
  { id: '175', name: 'Fluid Culture & Sensitivity (Aerobic)', category: 'Culture', price: 600, description: 'Culture of body fluid.' },
  { id: '176', name: 'Fluid Cytology (Malignant cells)', category: 'Biopsy', price: 600, description: 'Cytology of body fluid for malignancy.' },
  { id: '177', name: 'Fluid Glucose', category: 'Blood Test', price: 150, description: 'Measures glucose in body fluid.' },
  { id: '178', name: 'Fluid LDH', category: 'Blood Test', price: 400, description: 'Measures LDH in body fluid.' },
  { id: '179', name: 'Fluid Protein', category: 'Blood Test', price: 250, description: 'Measures protein in body fluid.' },
  { id: '180', name: 'Fluid Triglycerides', category: 'Blood Test', price: 400, description: 'Measures triglycerides in body fluid.' },
  { id: '181', name: 'Fluid Urea', category: 'Blood Test', price: 250, description: 'Measures urea in body fluid.' },
  { id: '182', name: 'Fluid Uric Acid', category: 'Blood Test', price: 250, description: 'Measures uric acid in body fluid.' },
  { id: '183', name: 'Folic Acid (Folate)', category: 'Blood Test', price: 800, description: 'Measures folate levels.' },
  { id: '184', name: 'Follicle Stimulating Hormone (FSH)', category: 'Hormone', price: 450, description: 'Measures FSH levels.' },
  { id: '185', name: 'Free T3 (FT3)', category: 'Hormone', price: 250, description: 'Measures free T3 levels.' },
  { id: '186', name: 'Free T4 (FT4)', category: 'Hormone', price: 250, description: 'Measures free T4 levels.' },
  { id: '187', name: 'Free Testosterone', category: 'Hormone', price: 1000, description: 'Measures free testosterone levels.' },
  { id: '188', name: 'Fungal Culture', category: 'Culture', price: 800, description: 'Culture for fungal growth.' },
  { id: '189', name: 'Fungal Smear (KOH Mount)', category: 'Culture', price: 300, description: 'Smear for fungal elements.' },
  { id: '190', name: 'G6PD (Glucose 6 Phosphate Dehydrogenase)', category: 'Blood Test', price: 600, description: 'Measures G6PD enzyme activity.' },
  { id: '191', name: 'Gamma Glutamyl Transferase (GGT)', category: 'Blood Test', price: 250, description: 'Measures GGT levels.' },
  { id: '192', name: 'Gastrin', category: 'Hormone', price: 1500, description: 'Measures gastrin levels.' },
  { id: '195', name: 'Giardia Antigen (Stool)', category: 'Immunology', price: 800, description: 'Tests for Giardia in stool.' },
  { id: '196', name: 'Glucose Fasting (F)', category: 'Diabetes', price: 60, description: 'Measures fasting blood sugar.' },
  { id: '197', name: 'Glucose Post Prandial (PP)', category: 'Diabetes', price: 60, description: 'Measures post-meal blood sugar.' },
  { id: '198', name: 'Glucose Random (R)', category: 'Diabetes', price: 60, description: 'Measures random blood sugar.' },
  { id: '199', name: 'Glycosylated Hemoglobin (HbA1c)', category: 'Diabetes', price: 400, description: 'Measures average blood sugar over 3 months.' },
  { id: '200', name: 'Gram Stain', category: 'Culture', price: 200, description: 'Stain for bacterial identification.' },
  { id: '201', name: 'Growth Hormone (GH) Fasting', category: 'Hormone', price: 600, description: 'Measures fasting growth hormone.' },
  { id: '202', name: 'Growth Hormone (GH) Post Exercise', category: 'Hormone', price: 600, description: 'Measures growth hormone after exercise.' },
  { id: '203', name: 'H. Pylori Antibody - IgG', category: 'Immunology', price: 600, description: 'Tests for H. pylori IgG.' },
  { id: '204', name: 'H. Pylori Antibody - IgM', category: 'Immunology', price: 600, description: 'Tests for H. pylori IgM.' },
  { id: '205', name: 'H. Pylori Antigen (Stool)', category: 'Immunology', price: 800, description: 'Tests for H. pylori antigen in stool.' },
  { id: '206', name: 'Hanta Virus IgM', category: 'Immunology', price: 1500, description: 'Tests for Hanta virus IgM.' },
  { id: '208', name: 'Hb Electrophoresis (HPLC)', category: 'Blood Test', price: 800, description: 'Analyzes hemoglobin types.' },
  { id: '209', name: 'HBsAg (CLIA)', category: 'Immunology', price: 400, description: 'Tests for Hepatitis B surface antigen.' },
  { id: '210', name: 'HBsAg (ELISA)', category: 'Immunology', price: 400, description: 'Tests for Hepatitis B surface antigen.' },
  { id: '211', name: 'HBsAg (Rapid)', category: 'Immunology', price: 150, description: 'Rapid test for Hepatitis B surface antigen.' },
  { id: '212', name: 'HBV DNA Quantitative (Real time PCR)', category: 'Blood Test', price: 4500, description: 'Measures HBV viral load.' },
  { id: '213', name: 'HCV Antibody (CLIA)', category: 'Immunology', price: 700, description: 'Tests for Hepatitis C antibodies.' },
  { id: '214', name: 'HCV Antibody (ELISA)', category: 'Immunology', price: 700, description: 'Tests for Hepatitis C antibodies.' },
  { id: '215', name: 'HCV Antibody (Rapid)', category: 'Immunology', price: 300, description: 'Rapid test for Hepatitis C antibodies.' },
  { id: '216', name: 'HCV RNA Quantitative (Real time PCR)', category: 'Blood Test', price: 4500, description: 'Measures HCV viral load.' },
  { id: '217', name: 'HEV IgM antibody', category: 'Immunology', price: 800, description: 'Tests for Hepatitis E IgM.' },
  { id: '218', name: 'Hemoglobin (Hb)', category: 'Blood Test', price: 60, description: 'Measures hemoglobin levels.' },
  { id: '219', name: 'Herpes Simplex Virus (HSV) 1 IgG', category: 'Immunology', price: 600, description: 'Tests for HSV-1 IgG.' },
  { id: '220', name: 'Herpes Simplex Virus (HSV) 1 IgM', category: 'Immunology', price: 600, description: 'Tests for HSV-1 IgM.' },
  { id: '221', name: 'Herpes Simplex Virus (HSV) 2 IgG', category: 'Immunology', price: 600, description: 'Tests for HSV-2 IgG.' },
  { id: '222', name: 'Herpes Simplex Virus (HSV) 2 IgM', category: 'Immunology', price: 600, description: 'Tests for HSV-2 IgM.' },
  { id: '223', name: 'Herpes Simplex Virus (HSV) 1 & 2 IgG', category: 'Immunology', price: 1000, description: 'Tests for HSV-1 & 2 IgG.' },
  { id: '224', name: 'Herpes Simplex Virus (HSV) 1 & 2 IgM', category: 'Immunology', price: 1000, description: 'Tests for HSV-1 & 2 IgM.' },
  { id: '225', name: 'High Sensitivity C-Reactive Protein (hs-CRP)', category: 'Heart', price: 600, description: 'Measures cardiac risk.' },
  { id: '226', name: 'Histopathology -Large >3 cm', category: 'Biopsy', price: 1200, description: 'Biopsy of large tissue mass.' },
  { id: '227', name: 'Histopathology -Medium 1-3 cm', category: 'Biopsy', price: 750, description: 'Biopsy of medium tissue mass.' },
  { id: '228', name: 'Histopathology -small <1cm', category: 'Biopsy', price: 600, description: 'Biopsy of small tissue mass.' },
  { id: '229', name: 'HIV 1 & 2 Antibody (CLIA)', category: 'Immunology', price: 500, description: 'Tests for HIV antibodies.' },
  { id: '230', name: 'HIV 1 & 2 Antibody (ELISA)', category: 'Immunology', price: 500, description: 'Tests for HIV antibodies.' },
  { id: '231', name: 'HIV 1 & 2 Antibody (Rapid)', category: 'Immunology', price: 250, description: 'Rapid test for HIV antibodies.' },
  { id: '232', name: 'HIV p24 Antigen & Antibody (4th Generation)', category: 'Immunology', price: 700, description: 'Tests for HIV antigen and antibodies.' },
  { id: '233', name: 'HLA B27 (Flowcytometry)', category: 'Immunology', price: 2500, description: 'Tests for HLA-B27 antigen.' },
  { id: '234', name: 'Homocysteine', category: 'Heart', price: 1000, description: 'Measures homocysteine levels.' },
  { id: '235', name: 'Hydatid Cyst (Echinococcus) IgG', category: 'Immunology', price: 1000, description: 'Tests for Hydatid cyst IgG.' },
  { id: '236', name: 'Indirect Coomb\'s Test (ICT)', category: 'Blood Test', price: 500, description: 'Tests for antibodies against RBCs.' },
  { id: '237', name: 'Insulin - Fasting', category: 'Diabetes', price: 600, description: 'Measures fasting insulin.' },
  { id: '238', name: 'Insulin - Post Prandial', category: 'Diabetes', price: 600, description: 'Measures post-meal insulin.' },
  { id: '239', name: 'Insulin - Random', category: 'Diabetes', price: 600, description: 'Measures random insulin.' },
  { id: '240', name: 'Intact Parathyroid Hormone (iPTH)', category: 'Hormone', price: 1200, description: 'Measures iPTH levels.' },
  { id: '241', name: 'Interleukin-6 (IL-6)', category: 'Blood Test', price: 2000, description: 'Measures IL-6 levels.' },
  { id: '242', name: 'Iron', category: 'Blood Test', price: 300, description: 'Measures serum iron.' },
  { id: '243', name: 'Iron Profile (Iron, TIBC, % Saturation)', category: 'Blood Test', price: 600, description: 'Comprehensive iron studies.' },
  { id: '244', name: 'Islet Cell Antibody', category: 'Diabetes', price: 1800, description: 'Tests for islet cell antibodies.' },
  { id: '245', name: 'Kappa Light Chain - Free', category: 'Blood Test', price: 2500, description: 'Measures free kappa light chains.' },
  { id: '246', name: 'Kidney Panel (KFT)', category: 'Kidney', price: 600, description: 'Kidney function tests.' },
  { id: '247', name: 'Kidney Panel (KFT) with Electrolytes', category: 'Kidney', price: 800, description: 'KFT with electrolytes.' },
  { id: '248', name: 'Lambda Light Chain - Free', category: 'Blood Test', price: 2500, description: 'Measures free lambda light chains.' },
  { id: '249', name: 'LDH (Lactate Dehydrogenase)', category: 'Blood Test', price: 300, description: 'Measures LDH enzyme activity.' },
  { id: '250', name: 'LE Cell Phenomenon', category: 'Immunology', price: 400, description: 'Tests for systemic lupus erythematosus.' },
  { id: '251', name: 'Leptospira IgG antibody', category: 'Immunology', price: 800, description: 'Tests for Leptospira IgG.' },
  { id: '252', name: 'Leptospira IgM antibody', category: 'Immunology', price: 800, description: 'Tests for Leptospira IgM.' },
  { id: '253', name: 'LH (Luteinizing Hormone)', category: 'Hormone', price: 450, description: 'Measures LH levels.' },
  { id: '254', name: 'Lipase', category: 'Blood Test', price: 400, description: 'Measures lipase enzyme activity.' },
  { id: '255', name: 'Lipid Profile (Chol, Trig, HDL, LDL, VLDL)', category: 'Heart', price: 500, description: 'Comprehensive cholesterol screening.' },
  { id: '257', name: 'Liver Panel (LFT)', category: 'Liver', price: 500, description: 'Liver function tests.' },
  { id: '258', name: 'Liver Panel (LFT) with GGT', category: 'Liver', price: 600, description: 'LFT with GGT.' },
  { id: '260', name: 'Lupus Anticoagulant (LA)', category: 'Immunology', price: 1500, description: 'Tests for lupus anticoagulant.' },
  { id: '261', name: 'Magnesium', category: 'Blood Test', price: 350, description: 'Measures magnesium levels.' },
  { id: '262', name: 'Malaria Parasite (MP) - Smear', category: 'Blood Test', price: 150, description: 'Smear for malaria parasite.' },
  { id: '263', name: 'Malaria Parasite (MP) - Rapid (Antigen)', category: 'Blood Test', price: 250, description: 'Rapid test for malaria antigen.' },
  { id: '264', name: 'Mantoux Test', category: 'Immunology', price: 200, description: 'Skin test for tuberculosis.' },
  { id: '265', name: 'Measles (Rubeola) IgG', category: 'Immunology', price: 800, description: 'Tests for measles IgG.' },
  { id: '266', name: 'Measles (Rubeola) IgM', category: 'Immunology', price: 800, description: 'Tests for measles IgM.' },
  { id: '267', name: 'Microalbumin (Spot Urine)', category: 'Urine Test', price: 500, description: 'Measures microalbumin in spot urine.' },
  { id: '268', name: 'Microalbumin (24 hrs Urine)', category: 'Urine Test', price: 700, description: 'Measures microalbumin in 24hr urine.' },
  { id: '269', name: 'Mouth biopsy -small <1cm', category: 'Biopsy', price: 600, description: 'Biopsy of small mouth mass.' },
  { id: '270', name: 'Mumps IgG', category: 'Immunology', price: 800, description: 'Tests for mumps IgG.' },
  { id: '271', name: 'Mumps IgM', category: 'Immunology', price: 800, description: 'Tests for mumps IgM.' },
  { id: '272', name: 'Myoglobin', category: 'Heart', price: 1000, description: 'Measures myoglobin levels.' },
  { id: '273', name: 'Nasal Swab for Eosinophils', category: 'Blood Test', price: 200, description: 'Tests for eosinophils in nasal swab.' },
  { id: '274', name: 'NT-pro BNP', category: 'Heart', price: 2500, description: 'Tests for heart failure.' },
  { id: '275', name: 'Osteocalcin', category: 'Blood Test', price: 2000, description: 'Measures osteocalcin levels.' },
  { id: '276', name: 'Pap Smear (Conventional)', category: 'Biopsy', price: 600, description: 'Conventional Pap smear.' },
  { id: '277', name: 'Pap Smear (LBC)', category: 'Biopsy', price: 1200, description: 'Liquid-based cytology Pap smear.' },
  { id: '278', name: 'Peripheral Smear for Malignant cells', category: 'Biopsy', price: 400, description: 'Smear for malignant cells.' },
  { id: '279', name: 'Peripheral Smear for Morphology', category: 'Blood Test', price: 200, description: 'Smear for cell morphology.' },
  { id: '280', name: 'Phosphorus', category: 'Blood Test', price: 200, description: 'Measures phosphorus levels.' },
  { id: '281', name: 'Plasma Hemoglobin', category: 'Blood Test', price: 600, description: 'Measures plasma hemoglobin.' },
  { id: '282', name: 'Platelet Count', category: 'Blood Test', price: 100, description: 'Measures platelet count.' },
  { id: '283', name: 'Pleural Fluid Analysis (Routine)', category: 'Blood Test', price: 600, description: 'Routine analysis of pleural fluid.' },
  { id: '284', name: 'Potassium', category: 'Blood Test', price: 200, description: 'Measures potassium levels.' },
  { id: '285', name: 'Procalcitonin (PCT)', category: 'Blood Test', price: 2000, description: 'Marker for severe infection/sepsis.' },
  { id: '286', name: 'Progesterone', category: 'Hormone', price: 500, description: 'Measures progesterone levels.' },
  { id: '287', name: 'Prolactin', category: 'Hormone', price: 450, description: 'Measures prolactin levels.' },
  { id: '288', name: 'Prostate Specific Antigen (PSA) - Total', category: 'Blood Test', price: 600, description: 'Tumor marker for prostate.' },
  { id: '289', name: 'Prostate Specific Antigen (PSA) - Free', category: 'Blood Test', price: 1000, description: 'Tumor marker for prostate.' },
  { id: '290', name: 'Protein - Total (Serum)', category: 'Blood Test', price: 150, description: 'Measures total serum protein.' },
  { id: '291', name: 'Protein - Total with Albumin/Globulin', category: 'Blood Test', price: 250, description: 'Total protein with A/G ratio.' },
  { id: '292', name: 'Protein Electrophoresis (Serum)', category: 'Blood Test', price: 800, description: 'Analyzes serum protein types.' },
  { id: '293', name: 'Prothrombin Time (PT) with INR', category: 'Blood Test', price: 350, description: 'Measures blood clotting time.' },
  { id: '294', name: 'Quadruple Marker', category: 'Hormone', price: 3500, description: 'Prenatal screening test.' },
  { id: '295', name: 'RA Factor (Qualitative)', category: 'Immunology', price: 300, description: 'Qualitative test for RA factor.' },
  { id: '297', name: 'Reticulocyte Count', category: 'Blood Test', price: 250, description: 'Measures reticulocyte count.' },
  { id: '298', name: 'Rheumatoid Factor (RA) - Quantitative', category: 'Immunology', price: 500, description: 'Quantitative test for RA factor.' },
  { id: '299', name: 'Rubella - IgG', category: 'Immunology', price: 500, description: 'Tests for Rubella IgG.' },
  { id: '300', name: 'Rubella - IgM', category: 'Immunology', price: 550, description: 'Tests for Rubella IgM.' },
  { id: '301', name: 'S. Albumin', category: 'Blood Test', price: 150, description: 'Measures serum albumin.' },
  { id: '302', name: 'S. Amylase', category: 'Blood Test', price: 300, description: 'Measures serum amylase.' },
  { id: '303', name: 'S. Bilirubin', category: 'Liver', price: 150, description: 'Measures serum bilirubin.' },
  { id: '304', name: 'S. Calcium', category: 'Blood Test', price: 200, description: 'Measures serum calcium.' },
  { id: '305', name: 'S. Creatinine', category: 'Kidney', price: 150, description: 'Measures serum creatinine.' },
  { id: '307', name: 'S. Uric Acid', category: 'Kidney', price: 150, description: 'Measures serum uric acid.' },
  { id: '308', name: 'Salmonella Typhi IgG & IgM (Rapid)', category: 'Immunology', price: 400, description: 'Rapid test for Salmonella typhi.' },
  { id: '309', name: 'Scub Typhus antibody (Rapid)', category: 'Immunology', price: 800, description: 'Rapid test for Scrub Typhus.' },
  { id: '310', name: 'Semen Analysis', category: 'Culture', price: 300, description: 'Routine analysis of semen.' },
  { id: '311', name: 'Semen Fructose', category: 'Culture', price: 300, description: 'Measures fructose in semen.' },
  { id: '312', name: 'Serum Protein Electrophoresis', category: 'Blood Test', price: 800, description: 'Analyzes serum protein types.' },
  { id: '313', name: 'Sickle Cell Test (Solubility)', category: 'Blood Test', price: 400, description: 'Tests for sickle cell hemoglobin.' },
  { id: '314', name: 'Skin biopsy -small <1cm', category: 'Biopsy', price: 600, description: 'Biopsy of small skin mass.' },
  { id: '315', name: 'Skin Scraping for Fungus (KOH)', category: 'Culture', price: 300, description: 'Scraping for fungal elements.' },
  { id: '316', name: 'Sodium', category: 'Blood Test', price: 200, description: 'Measures sodium levels.' },
  { id: '317', name: 'Sputum for AFB (Acid Fast Bacilli)', category: 'Culture', price: 200, description: 'Tests for TB in sputum.' },
  { id: '318', name: 'Sputum for Malignant cells', category: 'Biopsy', price: 400, description: 'Tests for malignant cells in sputum.' },
  { id: '319', name: 'Stool for Occult Blood', category: 'Blood Test', price: 200, description: 'Tests for hidden blood in stool.' },
  { id: '320', name: 'Stool for Reducing Sugar', category: 'Blood Test', price: 200, description: 'Tests for reducing sugars in stool.' },
  { id: '321', name: 'Stool Routine & Microscopy', category: 'Blood Test', price: 150, description: 'Routine analysis of stool.' },
  { id: '322', name: 'Synovial Fluid Analysis', category: 'Blood Test', price: 600, description: 'Analysis of synovial fluid.' },
  { id: '323', name: 'Syphilis (VDRL)', category: 'Immunology', price: 150, description: 'Tests for syphilis.' },
  { id: '324', name: 'T3, T4, TSH (Total)', category: 'Hormone', price: 350, description: 'Comprehensive thyroid profile.' },
  { id: '325', name: 'Testosterone - Total', category: 'Hormone', price: 500, description: 'Measures total testosterone.' },
  { id: '326', name: 'Throat Swab for KLB (Diphtheria)', category: 'Culture', price: 300, description: 'Tests for diphtheria.' },
  { id: '327', name: 'Thyroid Peroxidase Antibody (TPO)', category: 'Hormone', price: 800, description: 'Tests for thyroid antibodies.' },
  { id: '328', name: 'Thyroid Profile (T3, T4, TSH)', category: 'Hormone', price: 350, description: 'Comprehensive thyroid profile.' },
  { id: '329', name: 'Thyroid Stimulating Hormone (TSH)', category: 'Hormone', price: 200, description: 'Measures TSH levels.' },
  { id: '330', name: 'Thyroglobulin Antibody (Anti-Tg)', category: 'Hormone', price: 1000, description: 'Tests for thyroglobulin antibodies.' },
  { id: '331', name: 'Thyroxine (T4)', category: 'Hormone', price: 150, description: 'Measures T4 levels.' },
  { id: '332', name: 'Tissue biopsy -Large >3 cm', category: 'Biopsy', price: 1200, description: 'Biopsy of large tissue mass.' },
  { id: '333', name: 'Tissue biopsy -Medium 1-3 cm', category: 'Biopsy', price: 750, description: 'Biopsy of medium tissue mass.' },
  { id: '334', name: 'Tissue biopsy -small <1cm', category: 'Biopsy', price: 600, description: 'Biopsy of small tissue mass.' },
  { id: '335', name: 'Tongue biopsy -small <1cm', category: 'Biopsy', price: 600, description: 'Biopsy of small tongue mass.' },
  { id: '336', name: 'TORCH - IgG (4 tests)', category: 'Immunology', price: 1200, description: 'Prenatal screening for 4 infections (IgG).' },
  { id: '337', name: 'TORCH - IgG & IgM (8 tests)', category: 'Immunology', price: 2500, description: 'Comprehensive prenatal screening for 8 infections.' },
  { id: '338', name: 'TORCH - IgM (4 tests)', category: 'Immunology', price: 1400, description: 'Prenatal screening for 4 infections (IgM).' },
  { id: '339', name: 'TORCH - IgG (5 tests)', category: 'Immunology', price: 1500, description: 'Prenatal screening for 5 infections (IgG).' },
  { id: '340', name: 'TORCH - IgM (5 tests)', category: 'Immunology', price: 1800, description: 'Prenatal screening for 5 infections (IgM).' },
  { id: '341', name: 'Total Protein', category: 'Blood Test', price: 150, description: 'Measures total protein in blood.' },
  { id: '342', name: 'Total IgE', category: 'Immunology', price: 600, description: 'Measures total IgE levels.' },
  { id: '343', name: 'Toxoplasma - IgG', category: 'Immunology', price: 400, description: 'Tests for Toxoplasma IgG.' },
  { id: '344', name: 'Toxoplasma - IgG & IgM', category: 'Immunology', price: 800, description: 'Combined test for Toxoplasma IgG and IgM.' },
  { id: '346', name: 'Toxoplasma - IgM', category: 'Immunology', price: 450, description: 'Tests for Toxoplasma IgM.' },
  { id: '347', name: 'Transferrin', category: 'Blood Test', price: 800, description: 'Measures transferrin levels.' },
  { id: '348', name: 'Transferrin Saturation', category: 'Blood Test', price: 600, description: 'Measures transferrin saturation.' },
  { id: '349', name: 'Triglycerides', category: 'Heart', price: 200, description: 'Measures triglyceride levels.' },
  { id: '350', name: 'Triiodothyronine (T3)', category: 'Hormone', price: 150, description: 'Measures T3 levels.' },
  { id: '351', name: 'Triple Marker', category: 'Hormone', price: 1500, description: 'Prenatal screening test.' },
  { id: '352', name: 'Troponin - I (Quantitative)', category: 'Heart', price: 1200, description: 'Measures troponin I levels.' },
  { id: '353', name: 'Troponin - T (Quantitative)', category: 'Heart', price: 1500, description: 'Measures troponin T levels.' },
  { id: '354', name: 'TSH Receptor Antibody', category: 'Hormone', price: 3500, description: 'Tests for Graves disease.' },
  { id: '355', name: 'Typhoid IgG & IgM (Rapid)', category: 'Immunology', price: 400, description: 'Rapid test for typhoid.' },
  { id: '356', name: 'Urea', category: 'Kidney', price: 150, description: 'Measures blood urea levels.' },
  { id: '357', name: 'Uric Acid', category: 'Kidney', price: 150, description: 'Measures uric acid levels.' },
  { id: '358', name: 'Urine Culture & Sensitivity (Aerobic)', category: 'Culture', price: 600, description: 'Urine culture for bacterial growth.' },
  { id: '359', name: 'Urine for Bence Jones Protein', category: 'Urine Test', price: 300, description: 'Tests for Bence Jones protein.' },
  { id: '360', name: 'Urine for Chyle', category: 'Urine Test', price: 300, description: 'Tests for chyle in urine.' },
  { id: '361', name: 'Urine for Glucose (Benedict\'s)', category: 'Urine Test', price: 100, description: 'Tests for glucose in urine.' },
  { id: '362', name: 'Urine for Ketone bodies', category: 'Urine Test', price: 100, description: 'Tests for ketones in urine.' },
  { id: '363', name: 'Urine for Microalbumin (Spot)', category: 'Urine Test', price: 500, description: 'Measures microalbumin in spot urine.' },
  { id: '364', name: 'Urine for Bile Salt & Bile Pigment', category: 'Urine Test', price: 100, description: 'Tests for bile salts and pigments in urine.' },
  { id: '365', name: 'Urine for Pregnancy Test (UPT)', category: 'Urine Test', price: 150, description: 'Rapid pregnancy test.' },
  { id: '366', name: 'Urine for Protein (Albumin)', category: 'Urine Test', price: 100, description: 'Tests for protein in urine.' },
  { id: '367', name: 'Urine for Reducing Sugar', category: 'Urine Test', price: 100, description: 'Tests for reducing sugars in urine.' },
  { id: '368', name: 'Urine Routine & Microscopy', category: 'Urine Test', price: 120, description: 'Routine analysis of urine.' },
  { id: '369', name: 'Urine Specific Gravity', category: 'Urine Test', price: 50, description: 'Measures concentration of urine.' },
  { id: '370', name: 'Urobilinogen', category: 'Urine Test', price: 100, description: 'Measures urobilinogen in urine.' },
  { id: '371', name: 'Valproic Acid', category: 'Blood Test', price: 1000, description: 'Measures valproic acid levels.' },
  { id: '372', name: 'Vancomycin', category: 'Blood Test', price: 2500, description: 'Measures vancomycin levels.' },
  { id: '373', name: 'Varicella Zoster Virus (VZV) IgG', category: 'Immunology', price: 800, description: 'Tests for VZV IgG.' },
  { id: '374', name: 'Varicella Zoster Virus (VZV) IgM', category: 'Immunology', price: 800, description: 'Tests for VZV IgM.' },
  { id: '375', name: 'Vitamin A', category: 'Blood Test', price: 2500, description: 'Measures Vitamin A levels.' },
  { id: '376', name: 'Vitamin B12', category: 'Blood Test', price: 600, description: 'Measures Vitamin B12 levels.' },
  { id: '377', name: 'Vitamin D (25-Hydroxy)', category: 'Blood Test', price: 800, description: 'Measures Vitamin D levels.' },
  { id: '378', name: 'Vitamin E', category: 'Blood Test', price: 2500, description: 'Measures Vitamin E levels.' },
  { id: '379', name: 'Vitamin K', category: 'Blood Test', price: 3500, description: 'Measures Vitamin K levels.' },
  { id: '380', name: 'VDRL (Qualitative)', category: 'Immunology', price: 150, description: 'Qualitative test for syphilis.' },
  { id: '381', name: 'Weil Felix Test', category: 'Immunology', price: 600, description: 'Tests for rickettsial infections.' },
  { id: '382', name: 'Western Blot for HIV 1', category: 'Immunology', price: 3500, description: 'Confirmatory test for HIV-1.' },
  { id: '383', name: 'Widal Test (Slide Agglutination)', category: 'Immunology', price: 200, description: 'Slide test for typhoid.' },
  { id: '384', name: 'Widal Test (Tube Agglutination)', category: 'Immunology', price: 300, description: 'Tube test for typhoid.' },
  { id: '385', name: 'X-Ray Chest PA View', category: 'Biopsy', price: 300, description: 'Chest X-ray PA view.' },
  { id: '386', name: 'X-Ray KUB', category: 'Biopsy', price: 400, description: 'KUB X-ray.' },
  { id: '387', name: 'X-Ray Spine Cervical AP/Lat', category: 'Biopsy', price: 600, description: 'Cervical spine X-ray.' },
  { id: '388', name: 'X-Ray Spine Lumbar AP/Lat', category: 'Biopsy', price: 600, description: 'Lumbar spine X-ray.' },
  { id: '389', name: 'X-Ray Spine Thoracic AP/Lat', category: 'Biopsy', price: 600, description: 'Thoracic spine X-ray.' },
  { id: '390', name: 'Zinc', category: 'Blood Test', price: 1000, description: 'Measures zinc levels.' },
  { id: '391', name: '17-Hydroxy Progesterone (17-OHP)', category: 'Hormone', price: 1000, description: 'Measures 17-OHP levels.' },
  { id: '392', name: '24 Hours Urine Protein', category: 'Urine Test', price: 400, description: 'Measures 24hr urine protein.' },
  { id: '393', name: '24 Hours Urine Creatinine', category: 'Urine Test', price: 400, description: 'Measures 24hr urine creatinine.' },
  { id: '394', name: '24 Hours Urine Sodium', category: 'Urine Test', price: 400, description: 'Measures 24hr urine sodium.' },
  { id: '395', name: '24 Hours Urine Potassium', category: 'Urine Test', price: 400, description: 'Measures 24hr urine potassium.' },
  { id: '396', name: '24 Hours Urine Chloride', category: 'Urine Test', price: 400, description: 'Measures 24hr urine chloride.' },
  { id: '397', name: '24 Hours Urine Uric Acid', category: 'Urine Test', price: 400, description: 'Measures 24hr urine uric acid.' },
  { id: '398', name: '24 Hours Urine Calcium', category: 'Urine Test', price: 400, description: 'Measures 24hr urine calcium.' },
  { id: '399', name: '24 Hours Urine Phosphorus', category: 'Urine Test', price: 400, description: 'Measures 24hr urine phosphorus.' },
  { id: '400', name: '24 Hours Urine Microalbumin', category: 'Urine Test', price: 600, description: 'Measures 24hr urine microalbumin.' },
];
